--Creating schema "Testorbit"

create database   `Testorbit`; 


--creating table for user_ROLES 'TESTORBIT_USER_ROLES'

CREATE TABLE TESTORBIT_USER_ROLES(
ROLE_ID INT(20) PRIMARY KEY,
ROLE_NAME VARCHAR(50) NOT NULL,
ROLE_DESC VARCHAR(50),
ROLE_STATUS CHAR(1) NOT NULL
);

--creating table for user_logins 'TESTORBIT_USER_REGISTRATION'

CREATE TABLE TESTORBIT_USER_REGISTRATION(
   USER_ID  BIGINT PRIMARY KEY AUTO_INCREMENT,
   EMPLOYEE_ID VARCHAR(50) NOT NULL,
   FIRST_NAME VARCHAR(50) NOT NULL,
   LAST_NAME VARCHAR(50),
   E_MAIL VARCHAR(50) NOT NULL,
   CONTACT_NO VARCHAR(12),
   USER_PASSWORD  VARCHAR(20) NOT NULL,
    USER_STATUS CHAR(1) NOT NULL,
   CREAT_DATE DATE,
   MODIFY_DATE DATE,
   ROLE_ID INT,
   MANAGER_ID  BIGINT,
   SUPER_MANAGER_ID BIGINT,
   CONSTRAINT FK_RoleId FOREIGN KEY (ROLE_ID)
    REFERENCES TESTORBIT_USER_ROLES(ROLE_ID)
  
);
--creating table for user_logins 'TESTORBIT_USER_REGISTRATION' MAPPING
CREATE TABLE TESTORBIT_USER_RESOURCE_MAPPING(
   MAPPING_ID  BIGINT PRIMARY key  AUTO_INCREMENT, 
   USER_ID_MANAGER  BIGINT,
   USER_ID_RESOURCE  BIGINT,
   APPROVED_STATUS CHAR(1) NOT NULL,
  
  CONSTRAINT FK_USR_MNGR FOREIGN KEY (USER_ID_MANAGER)
    REFERENCES TESTORBIT_USER_REGISTRATION(USER_ID),
    CONSTRAINT FK_USR_RCRC FOREIGN KEY (USER_ID_RESOURCE)
    REFERENCES TESTORBIT_USER_REGISTRATION(USER_ID)
);
--creating table for PROJECT 'TESTORBIT_MODULES'
CREATE TABLE TESTORBIT_MODULES(
MODULE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
MODULE_NAME VARCHAR(50) NOT NULL,
MODULE_DESC VARCHAR(200),
PROJECT_MANAGER_ID BIGINT,
TEST_MANAGER_ID BIGINT,
MODULE_STATUS VARCHAR(10) NOT NULL,
CREAT_DATE DATE,
END_DATE DATE,
START_DATE DATE,
	CONSTRAINT FK_PROJ_MNGR FOREIGN KEY (PROJECT_MANAGER_ID)
    REFERENCES TESTORBIT_USER_REGISTRATION(USER_ID)
   
);

CREATE TABLE `modules_to_testers` (
 `MODULE_TESTER_ID` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `TESTER_ID` BIGINT NOT NULL,
  `MODULE_ID` BIGINT NOT NULL,
 `MOD_TESTER_STATUS` CHAR(1) NOT NULL,
 CONSTRAINT FK_MODTES_TESTER FOREIGN KEY (TESTER_ID)
    REFERENCES TESTORBIT_USER_REGISTRATION(USER_ID),
     CONSTRAINT FK_MODTES_MOD FOREIGN KEY (MODULE_ID)
    REFERENCES TESTORBIT_MODULES(MODULE_ID)
    );

--creating table for TASKS 'TESTORBIT_TASKS'
CREATE TABLE TESTORBIT_TASKS(
TASK_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
TASK_DESC VARCHAR(200),
MODULE_ID BIGINT,
TEST_MANAGER_ID BIGINT,
TASK_STATUS VARCHAR(10) NOT NULL,
CREAT_DATE DATE,
END_DATE DATE,
START_DATE DATE,
	CONSTRAINT FK_TASK_TEST_MNGR FOREIGN KEY (TEST_MANAGER_ID)
    REFERENCES TESTORBIT_USER_REGISTRATION(USER_ID),
    CONSTRAINT FK_TASK_MOD FOREIGN KEY (MODULE_ID)
    REFERENCES TESTORBIT_MODULES(MODULE_ID)
);

--creating table for TASKS TO TESTER MAPPING 'TESTORBIT_TASKS_TO_TESTERS'
    CREATE TABLE TESTORBIT_TASKS_TO_TESTERS (
TASK_TESTER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
 TASK_ID BIGINT NOT NULL,
  TESTER_ID BIGINT NOT NULL,
 START_DATE DATE,
 CONSTRAINT FK_TASKTES_TESTER FOREIGN KEY (TESTER_ID)
    REFERENCES TESTORBIT_USER_REGISTRATION(USER_ID),
    CONSTRAINT FK_TASKTES_TASK FOREIGN KEY (TASK_ID)
    REFERENCES TESTORBIT_TASKS(TASK_ID)
 
  );
  
  --creating table for TEST_CASES 'TESTORBIT_TEST_CASES'
  CREATE TABLE TESTORBIT_TEST_CASES(
TESTCASE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
TESTCASE_INPUT VARCHAR(500),
TESTCASE_OUTPUT VARCHAR(500),
TESTCASE_COMMENTS VARCHAR(500),
TASK_ID BIGINT,
TESTER_ID BIGINT,
TESTCASE_STATUS CHAR(1) NOT NULL,
CREAT_DATE DATE,
END_DATE DATE,
	CONSTRAINT FK_TESTCASE_TESTER FOREIGN KEY (TESTER_ID)
    REFERENCES TESTORBIT_USER_REGISTRATION(USER_ID),
    CONSTRAINT FK_TASK_TESTCASE FOREIGN KEY (TASK_ID)
    REFERENCES TESTORBIT_TASKS(TASK_ID)
);

-- --creating table for TESTORBIT_HISTORY 'TESTORBIT_HISTORY'
CREATE TABLE TESTORBIT_HISTORY (
HISTORY_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
TASK_ID BIGINT NOT NULL,
TESTER_ID BIGINT NOT NULL,
MODULE_ID BIGINT,
TESTCASE_ID BIGINT,
EXECUTION_DATE DATE,
RESULT_STATUS VARCHAR(10) NOT NULL,
    CONSTRAINT FK_HISTORY_TESTER FOREIGN KEY (TESTER_ID)
    REFERENCES TESTORBIT_USER_REGISTRATION(USER_ID),
    CONSTRAINT FK_HISTORY_TASK FOREIGN KEY (TASK_ID)
    REFERENCES TESTORBIT_TASKS(TASK_ID),
    CONSTRAINT FK_HISTORY_MOD FOREIGN KEY (MODULE_ID)
    REFERENCES TESTORBIT_MODULES(MODULE_ID),
    CONSTRAINT FK_HISTORY_TESTCASE FOREIGN KEY (TESTCASE_ID)
    REFERENCES TESTORBIT_TEST_CASES(TESTCASE_ID)
);
INSERT INTO `testorbit`.`testorbit_user_roles`
(`ROLE_ID`,
`ROLE_NAME`,
`ROLE_DESC`,
`ROLE_STATUS`)
VALUES
(1001,
'Manager',
'Project Manger Admin',
'Y');
INSERT INTO `testorbit`.`testorbit_user_roles`
(`ROLE_ID`,
`ROLE_NAME`,
`ROLE_DESC`,
`ROLE_STATUS`)
VALUES
(1002,
'Test Manager',
'Project Test Manager',
'Y');

INSERT INTO `testorbit`.`testorbit_user_roles`
(`ROLE_ID`,
`ROLE_NAME`,
`ROLE_DESC`,
`ROLE_STATUS`)
VALUES
(1003,
'Testers',
'Project Testers',
'Y');


commit;

